Solution
mate-academy/rda_task_11_monitor_slow_queries pull request #7
Opened 2024-03-08 17:41 UTC by yaroslavyvk

2024-03-09 16:03 UTC, NazarSheremet requested changes
Need changes

2024-03-09 16:03 UTC, NazarSheremet commented on task.sql
>  	VALUES ('AwersomeProduct60');
No need to remove insert records from the Products1 table

2024-03-10 13:51 UTC, YuriiSmolii requested changes
Add EOF

2024-03-10 13:51 UTC, YuriiSmolii commented on task.sql
> +	VALUES ('AwersomeProduct60');
```suggestion
	VALUES ('AwersomeProduct60');

```

2024-03-11 12:43 UTC, NazarSheremet approved these changes
Good job!

2025-04-22 15:03 UTC, closed without merging